grafana:
    image: matisq/grafana:latest
    ports: 
        - 3000:3000
    links:
        - influxdb:influxdb
    environment:
        GF_INSTALL_PLUGINS: "alexanderzobnin-zabbix-app,bosun-app,briangann-gauge-panel,digiapulssi-breadcrumb-panel,grafana-clock-panel,grafana-example-app,grafana-influxdb-08-datasource,grafana-piechart-panel,grafana-simple-json-datasource,grafana-worldmap-panel,jdbranham-diagram-panel,kentik-app,mtanda-heatmap-epoch-panel,mtanda-histogram-panel,ns1-app,percona-percona-app,raintank-snap-app,raintank-worldping-app,savantly-heatmap-panel,sraoss-sunburst-panel,stagemonitor-elasticsearch-app,voxter-app"
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
        GF_SECURITY_SECRET_KEY: grafana
        GF_USERS_ALLOW_SIGN_UP: "true"
        GF_USERS_ALLOW_ORG_CREATE: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_NAME: grafana
        GF_DASHBOARDS_JSON_ENABLED: "true"
        GF_DASHBOARDS_JSON_PATH: /opt/grafana
    volumes_from:
        - grafana-data
    restart: always

grafana-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/grafana
        - /var/log/grafana
        - /var/lib/grafana/plugins

influxdb:
    image: matisq/influxdb:latest
    ports:
        - 8083:8083
        - 8086:8086
    environment:
        INFLUX_DATABASE: "test"
        INLFUX_ADMIN_USER: "snyh"
        INFLUX_ADMIN_PASS: "snyh"
    volumes_from:
        - influxdb-data

influxdb-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/influxdb
